--1번
SELECT DEPARTMENT_NAME "학과 명", CATEGORY "계열"
FROM TB_DEPARTMENT;

--2번
SELECT DEPARTMENT_NAME, '의 정원은', CAPACITY, '명 입니다.'
FROM TB_DEPARTMENT;

--3번
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IN ('001') ;

INTERSECT
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE ABSENCE_YN IN ('Y');

--DEPARTMENT_NO 학과번호
--ABSENCE_YN 휴학여부
--STUDENT_NAME 학생이름

--4번

--5번
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY >=20 AND CAPACITY <=30;

--6번



--7번
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;
--학과번호가 다 있는데? 미지정을 어케 조건잡지?

--8번
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NULL;

--9번
SELECT CATEGORY
FROM TB_DEPARTMENT;